### PR TITLE
clean up templates 

### PR DESCRIPTION
**Pull request by pkijowska**

### CODE REVIEW

**Review by christocarr — APPROVED** [review]
Looks good to me.

**Review by christocarr — APPROVED** [review]
Looks good to me.

**Review by christocarr — APPROVED** [review]
Looks good.

**Comment by pkijowska** [comment]
@christocarr I refectored the code and made an Input component for input and label and passed props to the child. It works in the same way but way much less code in resumeSlice and form component. I left the education section as it was. As there is also a label and input do you want to use the Input component instead or do you want to keep it as it is?

**Comment by christocarr** [comment]
> 

@pkijowska The idea behind the education and employment state is for the user to add more than just one for each case. Leave it as is and I will work on it if you want?

**Pull request merged**
